spring.datasource.url=jdbc:postgresql://localhost:5432/DocLink
spring.datasource.username=postgres
spring.datasource.password=Shane.malan.baines17
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080